### ISSUE TITLE
如何通过CDN方式使用？

### ISSUE THREAD

**Issue by abovesky** [hooray/vue-sku-form#12]
![image](https://user-images.githubusercontent.com/5986216/128964302-3bd8981e-36b2-42ed-b3b5-6f72b28b420f.png)
一直报错，请问如何解决？

**Comment by wangpeng1478** [comment]
同问

**Comment by wangpeng1478** [comment]
![image](https://user-images.githubusercontent.com/17980483/145972345-cc799962-9da6-43c1-ba69-d15ce9deb275.png)

**Comment by hooray** [comment]
不支持
