### ISSUE TITLE
创建了3 主规格 6个子规格 页面就卡住了

### ISSUE THREAD

**Issue by ZeroShiro** [hooray/vue-sku-form#16]
<img width="1455" alt="截屏2021-12-22 下午5 10 26" src="https://user-images.githubusercontent.com/48169665/147067326-d8e738eb-1612-4089-a0c2-3ca132d20382.png">

**Comment by ZeroShiro** [comment]
有什么方法可以 优化吗

**Comment by hooray** [comment]
暂时没有办法，建议从业务层面去控制下，我不清楚什么商品会有6*6*6=216个SKU
