### ISSUE TITLE
source-attribute数组格式不能实时push只能查询出来

### ISSUE THREAD

**Issue by huanghengchun** [hooray/vue-sku-form#2]
大佬 看能不搞成动态到然后直接push进去  不然需要自己新增一个然后查询出来
<img width="568" alt="WeChatf2015742380815b9cfaf9a0577e492b3" src="https://user-images.githubusercontent.com/54391640/101278151-7803e080-37f4-11eb-87ad-01c33600a32a.png">
<img width="677" alt="WeChatd6d626515626ea41f9d33cf1867c176a" src="https://user-images.githubusercontent.com/54391640/101278162-99fd6300-37f4-11eb-8de0-fe53eac5e954.png">

**Comment by huanghengchun** [comment]
this.sourceAttribute.push({
          name: '尺寸',
          item: ['S','M','L']
        })


不能实时显示 sourceAttribute数组有值  :source-attribute不能实时加载

**Comment by hooray** [comment]
@huanghengchun
可以手动进行下初始化，参考异步加载的[demo](https://hooray.github.io/vue-sku-form/examples/async-recovery.html)

**Comment by huanghengchun** [comment]
@hooray 感谢大哥
