### ISSUE TITLE
sku数据为空  库存价格等字段有值 数据显示不出来

### ISSUE THREAD

**Issue by huanghengchun** [hooray/vue-sku-form#3]
<img width="1543" alt="WeChat80e834725b81d98aa931d8dda37633e9" src="https://user-images.githubusercontent.com/54391640/104555731-54e11200-5679-11eb-9201-3390c0d51b63.png">
<img width="1477" alt="WeChatb5fb4fcfe1e02b722a62da632401c683" src="https://user-images.githubusercontent.com/54391640/104555802-6f1af000-5679-11eb-8b12-f3bdcd27619c.png">

**Comment by hooray** [comment]
重复问题，参见 #4
