### ISSUE TITLE
规格组能否动态添加

### ISSUE THREAD

**Issue by qq907274532** [hooray/vue-sku-form#6]
能否增加对规格组的操作(增加、删除)

**Comment by hooray** [comment]
目前不考虑这种设计。按我的设计是，规格（source-attribute）有独立的管理模块，而不是在配置 sku 的时候动态配置规格信息。好处是可以复用，例如有个规格数据池，商品分类关联需要的规格，在添加商品的时候自动调取规格数据进行 sku 表单初始化。
