### ISSUE TITLE
获取sku 数据时 可否拼接上每一项的name

### ISSUE THREAD

**Issue by Mr-Ooyo** [hooray/vue-sku-form#8]
获取sku 数据时 可否拼接上每一项的name 
譬如
[
  {
    "name": "颜色",
    "item": [
      "黑"
    ]
  }
]

sku拼接后
[
  {
    "sku": "颜色，黑",
    "price": 80,
    "stock": 100
  }
]

**Comment by hooray** [comment]
目前不考虑这样处理，会造成冗余数据。
生成返回的 sku 数据你可以自行做二次处理，通过 source-attribute 数据就可以处理成你想要的这种格式。
